### ISSUE TITLE
com.sun.jersey.api.MessageException: A message body writer for Java class, Error with v2.13.0

### ISSUE THREAD

**Issue by pgouda89** [FasterXML/jackson-jaxrs-providers#155]
We are having a jersey rest server using **jackson-jaxrs-json-provider** v2.12.6

I am seeing the following issue after upgrading  jackson-jaxrs-json-provider to 2.13.0

2022-01-27 08:22:12.810 PST : Caused by: com.sun.jersey.api.MessageException: A message body writer for Java class java.util.ArrayList, and Java type java.util.List<MyClass>, and MIME media type application/json was not found
2022-01-27 08:22:12.810 PST :     at java.lang.Thread.run(Thread.java:748)
2022-01-27 08:22:12.810 PST :     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2022-01-27 08:22:12.810 PST :     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-01-27 08:22:12.810 PST :     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-01-27 08:22:12.810 PST :     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2022-01-27 08:22:12.810 PST :     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
2022-01-27 08:22:12.810 PST :     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
2022-01-27 08:22:12.810 PST :     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2022-01-27 08:22:12.810 PST :     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
2022-01-27 08:22:12.810 PST :     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
2022-01-27 08:22:12.810 PST :     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
2022-01-27 08:22:12.810 PST :     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2022-01-27 08:22:12.810 PST :     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
2022-01-27 08:22:12.810 PST :     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
2022-01-27 08:22:12.810 PST :     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
2022-01-27 08:22:12.810 PST :     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
2022-01-27 08:22:12.810 PST :     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)

My web.xml
`
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://java.sun.com/xml/ns/javaee" xmlns:web="http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
	version="3.0">

	<display-name>MiService</display-name>
	<absolute-ordering />
	<servlet>
		<servlet-name>restService</servlet-name>
		<servlet-class>my.package.service.servlet.ServiceStartServlet</servlet-class>
		<init-param>
			<param-name>com.sun.jersey.config.property.packages</param-name>
			<param-value>my.package.service.rest.controller</param-value>
		</init-param>
		<init-param>
			<param-name>com.sun.jersey.api.json.POJOMappingFeature</param-name>
			<param-value>true</param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
	</servlet>
	<servlet-mapping>
		<servlet-name>restService</servlet-name>
		<url-pattern>/*</url-pattern>
	</servlet-mapping>
	<filter>
		<filter-name>AuthenticationFilter</filter-name>
		<filter-class>my.package.service.rest.auth.ServiceAuthenticationFilter</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>AuthenticationFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
</web-app>
`

ServiceStartServlet.java
![image](https://user-images.githubusercontent.com/45407645/151860286-07d009ca-0666-4476-a597-ffea81eb54f8.png)

Rest controller
![image](https://user-images.githubusercontent.com/45407645/151857967-32369367-406f-4ed6-be8c-8f8a1d7bd060.png)

Do we need to modify anything to use v2.13.0 of com.fasterxml.jackson.jaxrs.jackson-jaxrs-base and com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider?

**Comment by cowtowncoder** [comment]
I am not aware of changes between 2.12 and 2.13 that should cause compatibility issues.

This sounds like an issue with your JAX-RS platform/framework, whatever it is: maybe reach on their issue trackers or mailing lists.

**Comment by cowtowncoder** [comment]
Are you just messing with me? You did not include any relevant information about the framework and ask me to go look for link for you to click on?

Please go do your own research.

**Comment by GedMarc** [comment]
lol I got to the point where the problem lies between the keyboard and the chair and... just walk away xD xD
in a nutshell yes it is a framework usage error.

**Comment by pgouda89** [comment]
@GedMarc  I appreciate your reply, If it is a framework issue why does it happen only with jackson-jaxrs-base and jackson-jaxrs-json-provider version 2.13.x? Working fine in 2.12.6.

**Comment by GedMarc** [comment]
I do believe you have updated much more than that sir
Most certainly you have changed your jersey version or forgot your reference updates - xD 

```
<servlet-name>myrest</servlet-name>
<servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
 ```
 
Jersey 1.x servlet container reference mmm ;) start there
  
  <dependency>
      <groupId>org.glassfish.jersey.media</groupId>
      <artifactId>jersey-media-json-jackson</artifactId>
  </dependency>
  
  Follow guide and confirm all setups - https://mkyong.com/webservices/jax-rs/json-example-with-jersey-jackson/

@pgouda89 as a point though, please use the communication channels before logging issues, community will assist with these sort of things a lot quicker :) 

Just a bit of tongue-in-cheek play :)

**Comment by jeremykwiatkowski** [comment]
For those who end up here from google (and are using an old JAX-RS 1.x version), this was indeed a change made in 2.13.0. See https://github.com/FasterXML/jackson-jaxrs-providers/issues/134 for the change.
