### ISSUE TITLE
XmlMapper Concurrency Issues - JsonMappingException: Not implemented (through reference chain: 

### ISSUE THREAD

**Issue by daviessd** [FasterXML/jackson-jaxrs-providers#79]
Hi

I am trying to optomise the conversion of POJO to XML and Back. I read that the XmlMapper is thread safe so I thought I would test an implementation that uses a singleton XmlMapper.

I have provided the test details below. We are using Java 1.7 and Maven 3 to build.

When I use more that 2 threads it fails with an exception (included below).

If I remove the line of code:
 `xmlMapper.configure(SerializationFeature.INDENT_OUTPUT, true);
`
It runs to end no matter how many threads I throw at it.

I also noticed that without the singleton (creating a new XmlMapper each time). I get the same error when I run up more that 2 threads. This means that I currently have code in a live deployment that could potentially fail.

Can you please help.

Stuart

**EXCEPTION**
```
com.fasterxml.jackson.databind.JsonMappingException: Not implemented (through reference chain: com.bt.consumer.commons.TestObject["value"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:339)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:299)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:342)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:219)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:119)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider.serializeValue(XmlSerializerProvider.java:92)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3613)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2980)
	at com.bt.consumer.commons.XmlMapperThreadSafeTest$TestThread.run(XmlMapperThreadSafeTest.java:88)
Caused by: java.lang.UnsupportedOperationException: Not implemented
	at org.codehaus.stax2.ri.Stax2WriterAdapter.writeRaw(Stax2WriterAdapter.java:380)
	at org.codehaus.stax2.ri.Stax2WriterAdapter.writeRaw(Stax2WriterAdapter.java:373)
	at com.fasterxml.jackson.dataformat.xml.util.DefaultXmlPrettyPrinter$Lf2SpacesIndenter.writeIndentation(DefaultXmlPrettyPrinter.java:508)
	at com.fasterxml.jackson.dataformat.xml.util.DefaultXmlPrettyPrinter.writeLeafElement(DefaultXmlPrettyPrinter.java:262)
	at com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator.writeString(ToXmlGenerator.java:589)
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:49)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
	at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:202)
	... 5 more

```
**DEPENDENCIES**
```
            <fasterxml.jackson.version>2.7.2</fasterxml.jackson.version>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-xml</artifactId>
                <version>${fasterxml.jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>${fasterxml.jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${fasterxml.jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${fasterxml.jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-joda</artifactId>
                <version>${fasterxml.jackson.version}</version>
            </dependency>

```
**CODE**
```
package //removed//
public class TestObject {
    String value = "HI";
    public String getValue() {
        return value;
    }
    public void setValue(String value) {
        this.value = value;
    }
}

package //removed//
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;

import com.fasterxml.jackson.datatype.joda.JodaModule;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

/**
 * Created by dev on 3/3/16.
 */
public class XmlMapperThreadSafeTest {

    static final int THREAD_COUNT = 100;
    private static ObjectMapper staticXmlMapper;
    private static TestThread[] threads = new TestThread[THREAD_COUNT];

    @Before
    public void before() {
        staticXmlMapper = createMapper();
    }

    private static ObjectMapper createMapper() {
        ObjectMapper xmlMapper = new XmlMapper();
        xmlMapper.registerModule(new JodaModule());
        xmlMapper.configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false);
        xmlMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        /**
         * This line causes an exception to be thrown if the test has more than one thread!
         */
        xmlMapper.configure(SerializationFeature.INDENT_OUTPUT, true);
        return xmlMapper;
    }

    @Test
    public void testMapper() {
        /**
         * Setup
         */
        for (int i=0;i < THREAD_COUNT;i++) {
            threads[i] = new TestThread(i);
        }
        /**
         * Start
         */
        long start = System.currentTimeMillis();
        for (int i=0;i < THREAD_COUNT;i++) {
            threads[i].start();
        }
        /**
         * Wait and test for failures
         */
        int countOfRunningThreads;
        do {
            countOfRunningThreads = 0;
            for (int i=0;i < THREAD_COUNT;i++) {
                if (threads[i].running) {
                    countOfRunningThreads++;
                }
                if (threads[i].failed != null) {
                    threads[i].failed.printStackTrace();
                    System.out.println("TIME TAKEN:"+(System.currentTimeMillis() - start));
                    Assert.fail("An Exception was thrown:"+threads[i].failed.getMessage());
                }
            }
        } while (countOfRunningThreads > 0);
        System.out.println("TIME TAKEN:"+(System.currentTimeMillis() - start));

    }

    public class TestThread extends Thread {
        public boolean running = false;
        public Exception failed = null;
        public int id;
        public TestThread(int id) {
            this.id = id;
        }
        public void run() {
            running = true;
            failed = null;
            try {
                TestObject tm = new TestObject();
                Assert.assertEquals("ID:"+id+":<TestObject xmlns=\"\"><value>HI</value></TestObject>", "ID:" + id + ":" + staticXmlMapper.writeValueAsString(tm));
            } catch (JsonProcessingException e) {
                failed = e;
            } finally {
                running = false;
            }

        }
    }
}
```

**Comment by cowtowncoder** [comment]
My guess is that you are not including a dependency to a good Stax implementation: Woodstox 5(.0.2) or Aalto 1.0 is recommended. The default Stax implementation that JDK bundles has many issues, unfortunately, and this sounds like it might be the root cause.

**Comment by cowtowncoder** [comment]
One note: problem is not due to thread-safety, as far as I can see, but due to Stax implementation not supporting Stax2 API; this is needed to be able to indent XML output.
So try adding Woodstox or Aalto dependency; JDK-bundled Stax implementation does not unfortunately work wrt indentation.
